### ISSUE TITLE
대상 파일 인코딩이 모두 같지 않으면 오류 발생

### ISSUE THREAD

**Issue by Gynephobia** [SecretU4/EZworkEra#26]
인코딩을 한 번만 입력받아 일괄적으로 적용해서 인코딩이 다른 파일이 하나라도 있으면 오류 발생

예)
eraTW\ERB\MOVEMENTS\BASE自然変動.ERB (932)
eraTW\ERB\MOVEMENTS\DRAW_MAP.ERB (UTF-8)

**Comment by SecretU4** [comment]
현재 버전에서 상정된 해당 문제를 해결할 수 있는 방법은 해당 프로세스를 인코딩에 따라 반복하는 것(932로 처리 후 결과물 저장하고 UTF-8로 재처리)입니다만, 해당 처리를 코드 작성중 고려하지 않은 경우 프로그램이 불안정하게 작동할 수 있습니다.
 오류가 발생하였다고 표시되면서 프로그램이 강제종료되지 않는다면 이는 상정된 경우입니다.
 다만 제가 생각하고 있는 경우가 아닐 수 있으니, 사용하신 기능을 알려주시면 감사하겠습니다.


 추후 코드적으로 인코딩이 다른 파일이 있다면 예비용 인코딩 입력을 받는 방안을 고려해보겠습니다.

**Comment by Gynephobia** [comment]
ERB메뉴의 CSV 변수추출에서 나왔으나 인코딩을 정하고 파일을 읽어들이는 전 메뉴에서 발생할 것 같습니다.
에러 발생 시 VS에서 예외처리가 되지 않았다고 하면서 아래와 같은 메시지가 나옵니다.

> 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence

파이썬은 잘 모르지만 위의 예외 발생 시 해당 파일에 대한 인코딩을 다시 입력받도록 해야 될 것 같습니다.

**Comment by SecretU4** [comment]
예외처리 안되었다고 오류가 뜨면 제 코드상 실수가 맞는 것 같네요. 시간 나면 바로 확인해보겠습니다.

원래대로라면 정한 인코딩으로 돌리다 예외가 발생하면 로그(csv_debug.log인가 그렇습니다.)에 특정 파일에서 인코딩 오류났다고 기록한 후 해당 파일은 통과하도록 되어있거든요.

**Comment by SecretU4** [comment]
일단 ERBLoad단에서 인코딩 오류시 예외처리하도록 해놓긴 했습니다. 하는 김에 필터링도 개선하고자 오프라인 던계에서 수정중입니다.

**Comment by SecretU4** [comment]
#28 에서 인코딩 오류시 예외처리를 통해 강제종료되지 않도록 수정했습니다. 다만 인코딩이 다를 시 해당 자료에서 정보를 추출하지 않고 통과하므로 제외된 파일의 인코딩으로 다시 돌리는 절차가 필요합니다.
